# Generated by Django 6.0.7 on 2026-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('image', models.ImageField(upload_to='books/')),
            ],
        ),
    ]
